spring:
  application:
    name: api-gateway

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

feign:
  hystrix:
    enabled: true

zuul:
  ignored-services: '*'
#  host:
#    connect-timeout-millis: 10000
#    socket-timeout-millis: 60000
  routes:
    feign-consumer: /feign-consumer/**
#      path: /feign-consumer/**
#      serviceId: FEIGN-CONSUMER
    hello-service:
      path: /hello-service/**
      serviceId: hello-service
    other:
      path: /**/hello
      url: forward:local

ribbon:
#路由转发请求的超时时间
  ReadTimeout: 5000
#创建请求连接的超时时间
  ConnectTimeout: 5000

#HystrixCommand执行超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000